# Generated by Django 5.2.6 on 2025-10-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.DeleteModel(
            name='PostViews',
        ),
    ]
